#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export PREZTODIR="$HOME/.dotfiles/prezto/"

# Source Prezto.
if [[ -s "$PREZTODIR/init.zsh" ]]; then
  source "$PREZTODIR/init.zsh"
fi

# Customize to your needs...
